function [collector_noW,collector_W ,estimator ,Beamformer,transmitter,ofdm_transim ,ofdm_recive] = ...
config(sig_param  , ULA_0AZ_24_09)

fc=sig_param.fc;
collector_noW = phased.Collector("Sensor" ,ULA_0AZ_24_09 , ...
    "WeightsInputPort" , false,'OperatingFrequency' , fc...
    ,'Wavefront','Plane');

collector_W = phased.Collector("Sensor" ,ULA_0AZ_24_09 , ...
    "WeightsInputPort" , true,'OperatingFrequency' ,fc, ...
    'Wavefront' , 'Plane');

estimator = phased.MVDREstimator('SensorArray',ULA_0AZ_24_09,...
    'OperatingFrequency',fc,'DOAOutputPort',true,'NumSignals',2);

 Beamformer = phased.MVDRBeamformer('SensorArray',ULA_0AZ_24_09 , ...
     'OperatingFrequency',fc,'WeightsOutputPort',true , ...
     'TrainingInputPort',false ,'DirectionSource','Input port' ...
     ,'DiagonalLoadingFactor',0);

transmitter = phased.Radiator("OperatingFrequency",sig_param.fc);

ofdm_transim  = phased.WidebandRadiator...
( "SampleRate",sig_param.ofdm_BW*64 ,"NumSubbands",64);

ofdm_recive  = phased.WidebandCollector...
("CarrierFrequency",sig_param.fc ,"SampleRate",sig_param.ofdm_BW ...
,"NumSubbands",2096,"Sensor",ULA_0AZ_24_09);


